# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
.rcpp_set_all_atomic <- function(x, rp) {
    invisible(.Call(`_mutatomic_rcpp_set_all_atomic`, x, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_32_atomic <- function(x, ind, rp) {
    invisible(.Call(`_mutatomic_rcpp_set_vind_32_atomic`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_64_atomic <- function(x, ind, rp) {
    invisible(.Call(`_mutatomic_rcpp_set_vind_64_atomic`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Logical <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_col_Logical`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Logical <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_row_Logical`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Integer <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_col_Integer`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Integer <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_row_Integer`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Numeric <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_col_Numeric`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Numeric <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_row_Numeric`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Character <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_col_Character`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Character <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_row_Character`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Complex <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_col_Complex`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Complex <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_row_Complex`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Raw <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_col_Raw`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Raw <- function(x, f) {
    invisible(.Call(`_mutatomic_rcpp_setapply_row_Raw`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_address <- function(x) {
    .Call(`_mutatomic_rcpp_address`, x)
}

#' @keywords internal
#' @noRd
.rcpp_list_bindings <- function(ref_address, env, ls) {
    .Call(`_mutatomic_rcpp_list_bindings`, ref_address, env, ls)
}

#' @keywords internal
#' @noRd
.rcpp_serial <- function(x) {
    .Call(`_mutatomic_rcpp_serial`, x)
}

#' @keywords internal
#' @noRd
.rcpp_is_ma <- function(x) {
    .Call(`_mutatomic_rcpp_is_ma`, x)
}

